services:
  - type: web
    name: xenovate
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max_old_space_size=450
    scaling:
      minInstances: 1
      maxInstances: 1 