services:
  - type: web
    name: xenovate
    env: node
    buildCommand: npm install && pip install -r backend/requirements.txt && npm run build
    startCommand: npm run start:all
    envVars:
      - key: NODE_VERSION
        value: 18.20.7
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000 