services:
  # Frontend Next.js application
  - type: web
    name: xenovate
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:all
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        fromEnv: NEXT_PUBLIC_SUPABASE_URL
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        fromEnv: NEXT_PUBLIC_SUPABASE_ANON_KEY
      - key: GEMINI_API_KEY
        fromEnv: GEMINI_API_KEY
      - key: NEXT_PUBLIC_API_URL
        value: /api
    routes:
      - type: rewrite
        source: /api/:path*
        destination: https://xenovate.onrender.com/api/:path*

  # Backend FastAPI application
  - type: web
    name: xenovate-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    routes:
      - type: rewrite
        source: /api/:path*
        destination: /:path* 