services:
  - type: web
    name: xenovate
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    plan: free 