services:
  - type: web
    name: xenovate
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: "--max_old_space_size=1024"
    autoDeploy: true
    plan: free 