name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install backend dependencies
        run: |
          cd xenovate/backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio
          
      - name: Install frontend dependencies
        run: |
          cd xenovate
          npm ci
        
      - name: Run backend tests
        run: |
          cd xenovate/backend
          pytest
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          
      - name: Run frontend tests
        run: |
          cd xenovate
          npm test
        
      - name: Build frontend
        run: |
          cd xenovate
          npm run build
        
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./xenovate
          file: ./xenovate/docker/Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xenovate-frontend:latest
          
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./xenovate
          file: ./xenovate/docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/xenovate-backend:latest 